### ISSUE TITLE
Sub-menu's collapse when clicked upon

### ISSUE THREAD

**Issue by pcable** [alpertuna/react-metismenu-router-link#1]
I'm attempting to replicate the demo functionality. However whenever I click on "sub-menu" the "Menu 3" collapses. I need this to remain open as it does in your demo.

- I copied the code from the website https://alpertuna.github.io/react-metismenu-router-link/
- Linked to the same style sheet.
- Used these libs:
    "bootstrap": "^3.3.7",
    "font-awesome": "^4.7.0",
    "jquery": "^3.1.1",
    "react": "^15.4.0",
    "react-bootstrap": "^0.30.6",
    "react-dom": "^15.4.0",
    "react-metismenu": "^1.1.3",
    "react-metismenu-router-link": "^1.0.0",
    "react-router": "^3.0.0"

But I must be missing something.

I can still navigate to the url and it will show the correct item. It's just this collapse on click that I need to change. Am I missing something or is this a bug. Which version is the demo using?

**Comment by alpertuna** [comment]
I got the point.
I tried and realized that there is a problematic part on demo as you are right.
`menu` content object assignment have to be at outside `App` render metod.
Since new content is created at each render, `react-metismenu` supposes content has been changed.

Wrong example;

``` javascript
const App = props = {
  const menu = [...];
  return <MetisMenu content={menu} />
}
```

Correct example;

``` javascript
const menu = [...];
const App = props = {
  return <MetisMenu content={menu} />
}
```

I will correct demo example source.

**Comment by pcable** [comment]
Thanks, that works great now.

**Comment by alpertuna** [comment]
Demo source example has been fixed. Thanks for your report :blush:
